export const phoneModels = [
  'iPhone 15 Pro Max',
  'iPhone 15 Pro',
  'iPhone 15',
  'iPhone 15 Plus',
  'iPhone 14 Pro Max',
  'iPhone 14 Pro',
  'iPhone 14',
  'iPhone 14 Plus',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro',
  'iPhone 13',
  'iPhone 13 mini',
  'iPhone 12 Pro Max',
  'iPhone 12 Pro',
  'iPhone 12',
  'iPhone 12 mini',
  'iPhone 11 Pro Max',
  'iPhone 11 Pro',
  'iPhone 11',
  'iPhone SE (2nd / 3rd Gen)',
  'iPhone 8',
  'iPhone 8 Plus',
  'Samsung Galaxy S24',
  'Samsung Galaxy S23',
  'Google Pixel 8',
  'Google Pixel 7',
]